name: word
channels:
  - conda-forge
  - damianavila82
dependencies:
  - python == 3.6
  - ipython
  - jupyter
  - tensorflow == 1.5
  - keras >= 2
  - gensim
  - matplotlib
  - numpy
  - scikit-learn
  - rise
  - pip